[package]
name = "veg"
version = "0.6.0"
edition = "2024"
description = "Flexible tables"
repository = "https://github.com/qtfkwk/veg"
license = "MIT"

[dependencies]
anyhow = "1.0.99"
colored = { version = "3.0.0", optional = true }
strip-ansi-escapes = { version = "0.2.1" }
unicode-segmentation = { version = "1.12.0" }

[features]
colored = ["dep:colored"]

[package.metadata.docs.rs]
features = ["colored"]
