[package]
name = "veg"
version = "0.4.1"
edition = "2021"
description = "Flexible tables"
repository = "https://github.com/qtfkwk/veg"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
colored = { version = "2.1.0", optional = true }
strip-ansi-escapes = { version = "0.2.0", optional = true }
unicode-segmentation = { version = "1.10.1", optional = true }

[features]
colored = ["dep:colored", "dep:strip-ansi-escapes", "dep:unicode-segmentation"]

